jobs:
  verify:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Initialize
        uses: actions/checkout@v2
      - name: Install Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Tests
        run: ./main/main

name: Run

on:
  schedule:
    - cron: "35 */6 * * *"
